### ISSUE TITLE
Make Node app display error when returned from Python Server

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#2]
## Current Tasks
- [ ] Slow Analysis for Remove capitalization (NNP) Word Tokenize (Spaces), Part of speech tagging

**Comment by kmp3325** [comment]
Lol nice: https://github.com/Pastafarians/linguine-node/blob/master/assets/js/analysis/new.controller.js#L140 .

This is likely not the only place we'll need to add error handling for though, but it's nice to know they had the TODO.

**Comment by kmp3325** [comment]
The front end was not carrying the error codes the back end sent back [here](https://github.com/Pastafarians/linguine-node/blob/4deba038a0ad666abb8151a3ab5870a37ce849fb/routes/analysis.js#L45).  I just chose to display generic error messages since changing the flow of this area is likely to change a lot with the errors that are possible.
