### ISSUE TITLE
Metadata should not be included in analysis

### ISSUE THREAD

**Issue by vastaj** [Pastafarians/linguine#8]
Metadata for the text is being included in the results of the analysis

**Comment by jmp3833** [comment]
Should get exact details reviewed by Ben in the next meeting.

**Comment by vastaj** [comment]
After talking to Ben and Cissi, this issue is likely the result of users included headers and/or footers in the corpus. It should be assumed that users will remove these manually, rather than use error checking for them.

**Comment by DanielleGonzalez** [comment]
From the 9/15 meeting with Ben & Cissi: 

Happens when Project Gutenburg files are uploaded
- metadata url included in word cloud
beginning & end of file -- prelude & footnotes 
either a pre-analysis warning or a detected indicator (possible preprocessing?) 
add tips for text to user docs? 
potential cleanup operation: url remover/html tag removal

**Comment by daniellegonzalez** [comment]
Add a warning re: this to the new 'documentation' tab

**Comment by jmp3833** [comment]
This will be resolved when documentation tasks are complete.
